version: '3'
services:
  db:
    image: postgres:10.3
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - 9001:5432
    expose:
      - "5432"
    volumes:
      - './postgres-data:/var/lib/postgresql'
  govote-server:
    build: './server'
    container_name: govote-server
    ports:
      - 3001:3001
    expose:
      - "3001"
    volumes:
      - './server:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    depends_on:
      - db
  govote-client:
    build: './client'
    container_name: govote-client
    ports:
      - 3000:3000
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - API_PROXY=http://govote-server:3001
    env_file: ./.env